iptail: <%= index+1 %>

localmirror: true

jobid: UNKNOWN
cluster: testcluster
profile: MASTER

domain: testcluster.cluster.local
#GENERATE with openssl passwd -1 $PASSWD
# This is 'password'.
encrypted_root_password: '$1$ljsJHJMq$aUpshtR7MKh3IjrFIUK9.1'

networks:
 - prv
 - mgt
 - ib

externaldns: 10.101.0.1

prvinterface: em1
prvip: 
prvnetmask: 255.255.0.0
prvnetwork: 10.10.0.0
prvgateway: 10.10.0.11

mgtinterface: em2
mgtip:
mgtnetmask: 255.255.0.0
mgtnetwork: 10.11.0.0
mgtgateway:

ibinterface: ib0
ibip:
ibnetmask: 255.255.0.0
ibnetwork: 10.12.0.0
ibgateway: 

bmcip:
bmcnetmask: 255.255.248.0
bmcnetwork: 172.16.139.0
bmcgateway: 0.0.0.0
bmcpassword: 'Scitjaf4'

disk: sda
