#!/bin/bash
#(c)2017 Alces Software Ltd. HPC Consulting Build Suite
#Job ID: <%= jobid%>
#Cluster: <%= cluster%>

export _ALCES_BASE_HOSTNAME=<%=nodename%>

#infra,compute
export _ALCES_PROFILE=<%=profile%>
export _ALCES_BUILDSERVER=<%=buildserver%>
export _ALCES_BUILDSERVEREXTERNALDNS=mycluster.mydomain.com #Used when configuring external facing http services (This must be live in your site DNS)

export _ALCES_CLUSTER=<%=cluster%>

export _ALCES_RELAYHOST=smtp.alces-software.com

export _ALCES_SSHKEY="AAAAB3NzaC1yc2EAAAADAQABAAABAQDhXUXuIDUG9BRva+m0BNSWg/E8OS7A153B1k0fUkSr2SNTUDRBIYNJ4XaX6l8HJNziugEeD2qhSX+qZT3jwr9t4tBcMh8hae72HXMaGPSQOFodNNAzaSAw8e5WYAbZAJnTMItrBkUO989ztwsAyfoeULxdW4ZRCpTECaqz1zklTEJxyUYwqJ3ar4n1cDdYsgXUldH2yopVSMx+EkH/NkQsg5GAqFJvP1yVvvhYgXBHF2tIA3iDWSU6HskAJpEIMjC0mxAWD0Gb3vNpPkp+1HbBPX1yp048EG4SF+jaLeJOrJqmMzngNuBJaUcNtP6UtsnCF7AVuCN1hAJxp1HKkY/v root@localhost.localdomain"

export _ALCES_YUMTEMPLATE=<%if localmirror%>yum.local<%else%>yum.upstream<%end%>

#GENERIC NETWORKING
export _ALCES_DOMAIN=<%=domain%>
export _ALCES_NETWORKS="<%=networks.join(" ")%>"
export _ALCES_SEARCHDOMAINS="prv.${_ALCES_DOMAIN} mgt.${_ALCES_DOMAIN} ib.${_ALCES_DOMAIN} ${_ALCES_DOMAIN}"
export _ALCES_EXTERNALDNS=<%=externaldns%>
export _ALCES_INTERNALDNS=${_ALCES_BUILDSERVER}


#SPECIFIC NETWORKING
export _ALCES_PRVINTERFACE="<%=prvinterface%>"
export _ALCES_PRVIP="<%=prvip%>"
export _ALCES_PRVNETMASK="<%=prvnetmask%>"
export _ALCES_PRVNETWORK="<%=prvnetwork%>"
export _ALCES_PRVGATEWAY="<%=prvgateway%>"
export _ALCES_PRVDOMAIN="prv.${_ALCES_DOMAIN}"
export _ALCES_PRVTYPE=

export _ALCES_MGTINTERFACE="<%=mgtinterface%>"
export _ALCES_MGTIP="<%=mgtip%>"
export _ALCES_MGTNETMASK="<%=mgtnetmask%>"
export _ALCES_MGTNETWORK="<%=mgtnetwork%>"
export _ALCES_MGTGATEWAY="<%=mgtgateway%>"
export _ALCES_MGTDOMAIN="mgt.${_ALCES_DOMAIN}"
export _ALCES_MGTTYPE=

export _ALCES_IBINTERFACE="<%=ibinterface%>"
export _ALCES_IBIP="<%=ibip%>"
export _ALCES_IBNETMASK="<%=ibnetmask%>"
export _ALCES_IBNETWORK="<%=ibnetwork%>"
export _ALCES_IBGATEWAY="<%=ibgateway%>"
export _ALCES_IBDOMAIN="ib.${_ALCES_DOMAIN}"
export _ALCES_IBTYPE=

export _ALCES_BOND0_OPTIONS="mode=1 primary=p3p2 miimon=80"
export _ALCES_BOND0_INTERFACES="em1 em2 p3p2"

export _ALCES_MGT_INTERFACES="em3"

#IPMI (BMC) NETWORKING
export _ALCES_BMCDOMAIN="bmc.${_ALCES_DOMAIN}"
export _ALCES_BMCPASSWORD="<%=bmcpassword%>"
export _ALCES_BMCIP="<%=bmcip%>"
export _ALCES_BMCNETMASK="<%=bmcnetmask%>"
export _ALCES_BMCNETWORK="<%=bmcnetwork%>"
export _ALCES_BMCGATEWAY="<%=bmcgateway%>"
export _ALCES_BMCCHANNEL=1
export _ALCES_BMCUSER=2


# Get Kernel cmdline options
params=`cat /proc/cmdline`
# Split them on spaces
params_split=(${params// / })
# Go through each of them
for p in "${params_split[@]}"; do
  # And if it's a key value pair
  if [[ $p =~ "=" ]]; then
    # And if the key doesn't have a period in it
    p_split=(${p//=/ })
    if [[ !($p_split[0] =~ ".") ]]; then
      # Then set the key to the value
      eval export $p;
    fi;
  fi
done

#Overwrite any _ALCES vars with any set ALCES vars
eval `compgen -v | grep ^ALCES | while read n; do echo _$n=\`eval "echo \\\\$$n"\`; done`


export _ALCES_KEYS=`compgen -v | grep _ALCES | while read n; do echo '$'$n; done | xargs`

install_file() {
  FILES_PATH=/opt/metalware/deployment/epel/files/
  FILES_URL=http://${_ALCES_BUILDSERVER}/deployment/epel/files/
  if [ -d $FILES_PATH ]; then
    cat $FILES_PATH/$1 | envsubst "$_ALCES_KEYS" > $2
  else
    curl $FILES_URL/$1 | envsubst "$_ALCES_KEYS" > $2
  fi
}

run_script() {
  SCRIPTS_PATH=/var/lib/metalware/rendered/scripts/${_ALCES_BASE_HOSTNAME}/
  SCRIPTS_URL=http://${_ALCES_BUILDSERVER}/metalware/scripts/${_ALCES_BASE_HOSTNAME}/
  if [ -d $SCRIPTS_PATH ]; then
    cat $SCRIPTS_PATH/$1 | bash
  else
    curl $SCRIPTS_URL/$1 | bash
  fi

}

run_profile() {
  run_script `echo $_ALCES_PROFILE | tr '[:upper:]' '[:lower:]'`.sh
}

get_value() {
  STR=`echo $1 | awk '{print toupper($0)}'`
  echo `eval "echo \\\$${STR}"`
}
